// JsFromRoutes CacheKey c6958d6aed4bce485288c976334d8c68
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/purchases/move'),
}
