// JsFromRoutes CacheKey 3d1c7c83e6ee47b69000f0f160d1df7e
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/purchases/:purchase_id/payments'),
  update: /* #__PURE__ */ definePathHelper('patch', '/purchases/:purchase_id/payments/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/purchases/:purchase_id/payments/:id'),
}
