// JsFromRoutes CacheKey 0066673bdbbd235122c6112d31332525
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/purchases/product_variants'),
}
