// JsFromRoutes CacheKey d15d5fef72d142893150105bea926333
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/brands'),
  create: /* #__PURE__ */ definePathHelper('post', '/brands'),
  new: /* #__PURE__ */ definePathHelper('get', '/brands/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/brands/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/brands/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/brands/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/brands/:id'),
}
