// JsFromRoutes CacheKey fcaae9bd9998c08445dab8be7985a4f4
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/colors'),
  create: /* #__PURE__ */ definePathHelper('post', '/colors'),
  new: /* #__PURE__ */ definePathHelper('get', '/colors/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/colors/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/colors/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/colors/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/colors/:id'),
}
