// JsFromRoutes CacheKey f26f30c677653e8f664713f73e23bcd5
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/customers/page/:page'),
  list: /* #__PURE__ */ definePathHelper('get', '/customers'),
  create: /* #__PURE__ */ definePathHelper('post', '/customers'),
  new: /* #__PURE__ */ definePathHelper('get', '/customers/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/customers/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/customers/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/customers/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/customers/:id'),
}
