// JsFromRoutes CacheKey 2359f0079b564e06f617a07170e85daf
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/'),
  noop: /* #__PURE__ */ definePathHelper('get', '/noop'),
}
