// JsFromRoutes CacheKey 9d48bf42ff5d6a838516be1b15977a73
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/expense_rates'),
  create: /* #__PURE__ */ definePathHelper('post', '/expense_rates'),
  new: /* #__PURE__ */ definePathHelper('get', '/expense_rates/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/expense_rates/:id/edit'),
  update: /* #__PURE__ */ definePathHelper('patch', '/expense_rates/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/expense_rates/:id'),
}
