// JsFromRoutes CacheKey fcc180bd6dbbc130e93be48adee7c1de
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/franchises'),
  create: /* #__PURE__ */ definePathHelper('post', '/franchises'),
  new: /* #__PURE__ */ definePathHelper('get', '/franchises/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/franchises/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/franchises/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/franchises/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/franchises/:id'),
}
