// JsFromRoutes CacheKey 033af524f3c8e8343c1f280e123912db
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/glossary'),
}
