// JsFromRoutes CacheKey e5dd1025ac1e84effeb631e9d39cd9bd
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/media/uploads'),
}
