// JsFromRoutes CacheKey b9c3256f9370b0eb69cef52084c3d43e
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/operational_expenses'),
  create: /* #__PURE__ */ definePathHelper('post', '/operational_expenses'),
  new: /* #__PURE__ */ definePathHelper('get', '/operational_expenses/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/operational_expenses/:id/edit'),
  update: /* #__PURE__ */ definePathHelper('patch', '/operational_expenses/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/operational_expenses/:id'),
}
