// JsFromRoutes CacheKey bd77f3c7257e905bf9ba64f6288f9270
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/passwords'),
  create: /* #__PURE__ */ definePathHelper('post', '/passwords'),
  new: /* #__PURE__ */ definePathHelper('get', '/passwords/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/passwords/:token/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/passwords/:token'),
  update: /* #__PURE__ */ definePathHelper('patch', '/passwords/:token'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/passwords/:token'),
}
