// JsFromRoutes CacheKey e6cb33bada1698ad79e3b0f619fb4f7c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/products/page/:page'),
  list: /* #__PURE__ */ definePathHelper('get', '/products'),
  create: /* #__PURE__ */ definePathHelper('post', '/products'),
  new: /* #__PURE__ */ definePathHelper('get', '/products/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/products/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/products/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/products/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/products/:id'),
}
