// JsFromRoutes CacheKey 77c1de8ea2b3b1097334866f676bd35d
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/purchases/page/:page'),
  list: /* #__PURE__ */ definePathHelper('get', '/purchases'),
  create: /* #__PURE__ */ definePathHelper('post', '/purchases'),
  new: /* #__PURE__ */ definePathHelper('get', '/purchases/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/purchases/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/purchases/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/purchases/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/purchases/:id'),
}
