// JsFromRoutes CacheKey b910953b543bbc29673d28b50f39590e
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/purchase_items'),
  edit: /* #__PURE__ */ definePathHelper('get', '/purchase_items/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/purchase_items/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/purchase_items/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/purchase_items/:id'),
}
