// JsFromRoutes CacheKey 261445a929bb9026925d522d50f24d44
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/sales/page/:page'),
  list: /* #__PURE__ */ definePathHelper('get', '/sales'),
  create: /* #__PURE__ */ definePathHelper('post', '/sales'),
  new: /* #__PURE__ */ definePathHelper('get', '/sales/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/sales/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/sales/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/sales/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/sales/:id'),
}
