// JsFromRoutes CacheKey 1f7e8b62c8aeb133a409fa50915890c9
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  edit: /* #__PURE__ */ definePathHelper('get', '/session/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/session'),
  update: /* #__PURE__ */ definePathHelper('patch', '/session'),
  create: /* #__PURE__ */ definePathHelper('post', '/session'),
  new: /* #__PURE__ */ definePathHelper('get', '/sign_in'),
  destroy: /* #__PURE__ */ definePathHelper('post', '/log_out'),
}
