// JsFromRoutes CacheKey 4f7f1af1cbed4fb3eb1a0e600549c19b
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/shipping_companies'),
  create: /* #__PURE__ */ definePathHelper('post', '/shipping_companies'),
  new: /* #__PURE__ */ definePathHelper('get', '/shipping_companies/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/shipping_companies/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/shipping_companies/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/shipping_companies/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/shipping_companies/:id'),
}
