// JsFromRoutes CacheKey 8398675aa0ef2a122b49262a3a6d73ef
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  new: /* #__PURE__ */ definePathHelper('get', '/sign_up/new'),
  create: /* #__PURE__ */ definePathHelper('post', '/sign_up'),
}
