// JsFromRoutes CacheKey be41020541a552dce4f8639394200a11
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/sizes'),
  create: /* #__PURE__ */ definePathHelper('post', '/sizes'),
  new: /* #__PURE__ */ definePathHelper('get', '/sizes/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/sizes/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/sizes/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/sizes/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/sizes/:id'),
}
