// JsFromRoutes CacheKey e443d2a97adc6bf714efcae301f48c96
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/suppliers'),
  create: /* #__PURE__ */ definePathHelper('post', '/suppliers'),
  new: /* #__PURE__ */ definePathHelper('get', '/suppliers/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/suppliers/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/suppliers/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/suppliers/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/suppliers/:id'),
}
