// JsFromRoutes CacheKey be94ced5f8b36b210c99b9b7ccd3a06a
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/users'),
  edit: /* #__PURE__ */ definePathHelper('get', '/users/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/users/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/users/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/users/:id'),
}
