// JsFromRoutes CacheKey 29c48a45b2684b039810e22ddffb8c73
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/variant_assignment_issues'),
}
