// JsFromRoutes CacheKey 2e5aa97bcecbc4cd89b473687f574e8e
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/versions'),
  create: /* #__PURE__ */ definePathHelper('post', '/versions'),
  new: /* #__PURE__ */ definePathHelper('get', '/versions/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/versions/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/versions/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/versions/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/versions/:id'),
}
