// JsFromRoutes CacheKey fcfda43a511576c76acc56090f57bb28
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/warehouses'),
  create: /* #__PURE__ */ definePathHelper('post', '/warehouses'),
  new: /* #__PURE__ */ definePathHelper('get', '/warehouses/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/warehouses/:id/edit'),
  update: /* #__PURE__ */ definePathHelper('patch', '/warehouses/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/warehouses/:id'),
}
