require:
  - standard
  - rubocop-slim
  - database_validations/rubocop/cops

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - node_modules/**/*
    - public/**/*
    - vendor/**/*

Rails:
  Enabled: true # enable rubocop-rails cops
Rails/I18nLocaleTexts:
  Enabled: false
Rails/UnknownEnv:
  Environments:
    - development
    - test
    - production
    - staging
Layout/ClassStructure:
  Enabled: true
  ExpectedOrder:
    - module_inclusion
    - constants
    - macros
    - public_class_methods
    - initializer
    - public_methods
    - protected_methods
    - private_methods
  Categories:
    association:
      - has_many
      - has_one
    attribute_macros:
      - attr_accessor
      - attr_reader
      - attr_writer
    macros:
      - validates
      - validate
    module_inclusion:
      - include
      - prepend
      - extend
RSpec:
  Enabled: true # enable rubocop-rspec cops
RSpec/DescribeClass:
  Enabled: false # ignore missing comments on classes
RSpec/MultipleMemoizedHelpers:
  Enabled: false # ignore multiple memoized helpers
RSpec/ExampleLength:
  Enabled: false
Bundler/DuplicatedGem:
  Enabled: false # ignore duplicated gem errors because we will have duplicated gems when dual booting
