require:
  - standard
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-slim
  - database_validations/rubocop/cops

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - node_modules/**/*
    - public/**/*
    - vendor/**/*

Rails:
  Enabled: true # enable rubocop-rails cops
RSpec:
  Enabled: true # enable rubocop-rspec cops
RSpec/DescribeClass:
  Enabled: false # ignore missing comments on classes
RSpec/MultipleMemoizedHelpers:
  Enabled: false # ignore multiple memoized helpers
Bundler/DuplicatedGem:
  Enabled: false # ignore duplicated gem errors because we will have duplicated gems when dual booting
Rails/I18nLocaleTexts:
  Enabled: false
