// JsFromRoutes CacheKey 6c27ce06c609108a5a4755cb92d95e0f
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/debts'),
  showGet: /* #__PURE__ */ definePathHelper('get', '/debts/:page'),
}
