// JsFromRoutes CacheKey 4f8974e264a56c1859fe7a9c1957c946
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/pull-last-orders'),
}
