// JsFromRoutes CacheKey fc459b4fb45e6c51ea3eab18b4bda391
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/sales/pull'),
}
