// JsFromRoutes CacheKey b4aea0db642bc84c3154a54c99035f40
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/sales/:sale_id/items/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/sales/:sale_id/items/:id'),
}
