// JsFromRoutes CacheKey be502b772ff45c73e2267a5f7bd00792
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/sales/:sale_id/pull'),
}
