// JsFromRoutes CacheKey 4582dce62c6fdd200d58afb0120895ee
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/sales/:sale_id/link_purchase_items'),
}
