// JsFromRoutes CacheKey f19e7f073a434b091c37d569e0adf554
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/purchase_items/:purchase_item_id/expenses'),
  update: /* #__PURE__ */ definePathHelper('patch', '/purchase_items/:purchase_item_id/expenses/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/purchase_items/:purchase_item_id/expenses/:id'),
}
