// JsFromRoutes CacheKey 16a8b856e3d532f53b5d2c1ce841209e
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  destroy: /* #__PURE__ */ definePathHelper('delete', '/purchase_items/:purchase_item_id/unlink'),
}
