// JsFromRoutes CacheKey 2745d39f7b353aaa7ae6cddff751e38a
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  destroy: /* #__PURE__ */ definePathHelper('delete', '/purchase_items/:purchase_item_id/sale_item_link'),
  create: /* #__PURE__ */ definePathHelper('post', '/purchase_items/:purchase_item_id/sale_item_link'),
}
