// JsFromRoutes CacheKey e58388cb1b3d5cb42ecd51a302bc8887
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  update: /* #__PURE__ */ definePathHelper('patch', '/purchase_items/:purchase_item_id/shipping_cost'),
}
