// JsFromRoutes CacheKey 8751619fdff192a09c842ceaebfe10f5
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  update: /* #__PURE__ */ definePathHelper('patch', '/purchase_items/:purchase_item_id/shipping_details'),
}
