// JsFromRoutes CacheKey c9ab5536eafc6735d13022d0331040cc
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  update: /* #__PURE__ */ definePathHelper('patch', '/purchase_items/:purchase_item_id/shipping_company'),
}
