// JsFromRoutes CacheKey 123c80915f16ce7b7b3b79e98ae85ab1
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  update: /* #__PURE__ */ definePathHelper('patch', '/purchase_items/:purchase_item_id/tracking_number'),
}
