// JsFromRoutes CacheKey aada93a9c414488f0a8510f4cbda4bbf
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/purchase_items/move'),
}
