// JsFromRoutes CacheKey f23688741ef5c77df9033d9e44dad5b4
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/warehouses/:id'),
  showGet: /* #__PURE__ */ definePathHelper('get', '/warehouses/:id/page/:page'),
}
