// JsFromRoutes CacheKey a41a156179508ef6aecb29b0e40cc53c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/warehouses/:warehouse_id/items'),
  new: /* #__PURE__ */ definePathHelper('get', '/warehouses/:warehouse_id/items/new'),
}
