// JsFromRoutes CacheKey 7b59f457d5af255704468fa26c4b2dd3
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  update: /* #__PURE__ */ definePathHelper('patch', '/warehouses/:warehouse_id/change_position'),
}
