// JsFromRoutes CacheKey 74da15d6b38272c30fe6fce9c514f3aa
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/variant_assignment_issues/backfill'),
}
