// JsFromRoutes CacheKey f9bc9aab00abdc30b5ea9776a29897c8
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  update: /* #__PURE__ */ definePathHelper('patch', '/variant_assignment_issues/purchase_item_links/:id'),
}
