// JsFromRoutes CacheKey 99e3db34b811452e183c08be85f3a58b
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  update: /* #__PURE__ */ definePathHelper('patch', '/variant_assignment_issues/purchases/:id'),
}
