// JsFromRoutes CacheKey 65c890147948a86c90e453880026e4b1
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  update: /* #__PURE__ */ definePathHelper('patch', '/variant_assignment_issues/sale_items/:id'),
}
