test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
  public: true

cloudflare:
  service: S3
  endpoint: https://<%= ENV["CLOUDFLARE_ACCOUNT_ID"] %>.eu.r2.cloudflarestorage.com
  access_key_id: <%= ENV["CLOUDFLARE_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["CLOUDFLARE_SECRET_ACCESS_KEY"] %>
  region: auto
  bucket: <%= ENV["CLOUDFLARE_BUCKET"] %>
  request_checksum_calculation: "when_required"
  response_checksum_validation: "when_required"
