// JsFromRoutes CacheKey cdb5433e73aafa7b1371d850cc173eb1
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/products/:product_id/assignable_variants'),
}
