// JsFromRoutes CacheKey 01ca8dcffc39280c514171269cf20afe
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/products/pull'),
}
