// JsFromRoutes CacheKey e53449d505f91498546f5589f20797f2
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/products/:product_id/shopify_push'),
}
