// JsFromRoutes CacheKey 6596a1fae3b7bb8455a9131149cccfdb
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/products/:product_id/shopify_pull'),
}
